micronaut:
  application:
    name: complete
  #tag::oauth2[]
  security:
    authentication: idtoken # <1>
    oauth2:
      clients:
        okta: # <2>
          client-secret: '${OAUTH_CLIENT_SECRET}' # <3>
          client-id: '${OAUTH_CLIENT_ID}' # <4>
          openid:
            issuer: 'http://localhost:8081/auth/realms/master'
    endpoints:
      logout:
        get-allowed: true # <6>
#end::oauth2[]
